services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173' # Map Vite dev server to localhost
    volumes:
      - .:/app # Mount source code for live reloading
      - /app/node_modules # Cache `node_modules` in the container
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures file watching works in Docker
